services:
  - type: web
    name: lr-billing-app
    env: node
    buildCommand: npm install && npx prisma generate && npx prisma db push && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 18.17.0
      - key: AWS_REGION
        value: ap-south-1
      - key: AWS_BUCKET_NAME
        value: lr-billing-invoices-mangesh

